spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: core-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis Plus 的配置项
mybatis-plus:
  # 虽然默认为 true ，但是还是显示去指定下。
  configuration:
    map-underscore-to-camel-case: true
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      id-type: NONE
      # 自增 ID，适合 MySQL 等直接自增的数据库
      #      id-type: AUTO
      # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      #      id-type: INPUT
      # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      #      id-type: ASSIGN_ID
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      logic-delete-field: deleted
    # 关闭控制台的 Banner 打印
    banner: true
  type-aliases-package: ${project.base-package}.module.dao
  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
  encryptor:
    # 加解密的秘钥，可使用 https://www.imaegoo.com/2020/aes-key-generator/ 网站生成
    password: XDV71a+xqStEA3WH


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

#使用代码生成模块时 指定要生成的表存在于哪种数据库，可选值有【mysql、oracle、sqlServer】
project:
  database: mysql
  base-package: com.example.core.admin

knife4j:
  # 开启增强配置
  enable: true
  setting:
    language: zh-CN

# Lock4j 配置项
lock4j:
  # 获取分布式锁超时时间，默认为 3000 毫秒
  acquire-timeout: 3000
  # 分布式锁的超时时间，默认为 30 毫秒
  expire: 30000
